services:
  postgres:
    image: postgres:16
    container_name: sms_saas_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sms_saas
      POSTGRES_USER: sms_admin
      POSTGRES_PASSWORD: sms_password
    ports:
      - "5432:5432"
    volumes:
      - sms_postgres_data:/var/lib/postgresql/data

volumes:
  sms_postgres_data:
